# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa194e4841954b04d91219e6465c3090d24e7a5f9cef487284d6d20e4e17c730113efbd8d2850f5104095e2a39690da5cefea0fe3207a36836f34070ff1d1822

test:
  secret_key_base: 3d6965bb65752f1cdfc464ec24e7a9a68640cf4ec0bc66c7d5cab6968fbc3945b8044379d3e09002cdb5087a029e7a49648b6acb29ecec917bde2fb093ed3e26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
